{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Importación de librerías"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).\n",
      "  from pandas.core import (\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "#from ydata_profiling import ProfileReport\n",
    "import dtale as dt\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "----\n",
    "\n",
    "##### Lectura de los datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id_cliente</th>\n",
       "      <th>edad</th>\n",
       "      <th>importe_solicitado</th>\n",
       "      <th>duracion_credito</th>\n",
       "      <th>antiguedad_empleado</th>\n",
       "      <th>situacion_vivienda</th>\n",
       "      <th>ingresos</th>\n",
       "      <th>objetivo_credito</th>\n",
       "      <th>pct_ingreso</th>\n",
       "      <th>tasa_interes</th>\n",
       "      <th>estado_credito</th>\n",
       "      <th>falta_pago</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>713061558.0</td>\n",
       "      <td>22</td>\n",
       "      <td>35000</td>\n",
       "      <td>3</td>\n",
       "      <td>123.0</td>\n",
       "      <td>ALQUILER</td>\n",
       "      <td>59000</td>\n",
       "      <td>PERSONAL</td>\n",
       "      <td>0.59</td>\n",
       "      <td>16.02</td>\n",
       "      <td>1</td>\n",
       "      <td>Y</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    id_cliente  edad  ...  estado_credito  falta_pago\n",
       "0  713061558.0    22  ...               1           Y\n",
       "\n",
       "[1 rows x 12 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_creditos = pd.read_csv(\"../../data/raw/datos_creditos.csv\", sep=\";\")\n",
    "df_creditos.head(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id_cliente</th>\n",
       "      <th>antiguedad_cliente</th>\n",
       "      <th>estado_civil</th>\n",
       "      <th>estado_cliente</th>\n",
       "      <th>gastos_ult_12m</th>\n",
       "      <th>genero</th>\n",
       "      <th>limite_credito_tc</th>\n",
       "      <th>nivel_educativo</th>\n",
       "      <th>nivel_tarjeta</th>\n",
       "      <th>operaciones_ult_12m</th>\n",
       "      <th>personas_a_cargo</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>713061558.0</td>\n",
       "      <td>36.0</td>\n",
       "      <td>CASADO</td>\n",
       "      <td>ACTIVO</td>\n",
       "      <td>1088.0</td>\n",
       "      <td>M</td>\n",
       "      <td>4010.0</td>\n",
       "      <td>UNIVERSITARIO_COMPLETO</td>\n",
       "      <td>Blue</td>\n",
       "      <td>24.0</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    id_cliente  antiguedad_cliente  ... operaciones_ult_12m personas_a_cargo\n",
       "0  713061558.0                36.0  ...                24.0              2.0\n",
       "\n",
       "[1 rows x 11 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_tarjetas = pd.read_csv(\"../../data/raw/datos_tarjetas.csv\", sep=\";\")\n",
    "df_tarjetas.head(1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "----\n",
    "\n",
    "##### Descripción de los datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def reporte_descripcion_dataset(df):\n",
    "    columnas = df.columns\n",
    "    print(\"Columnas del dataset:\\n\")\n",
    "    for col in columnas:\n",
    "        print(col)\n",
    "    print(f\"\\nCantidad de filas: {df.shape[0]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Descripción del dataset 'datos_creditos'\n",
      "Columnas del dataset:\n",
      "\n",
      "id_cliente\n",
      "edad\n",
      "importe_solicitado\n",
      "duracion_credito\n",
      "antiguedad_empleado\n",
      "situacion_vivienda\n",
      "ingresos\n",
      "objetivo_credito\n",
      "pct_ingreso\n",
      "tasa_interes\n",
      "estado_credito\n",
      "falta_pago\n",
      "\n",
      "Cantidad de filas: 10127\n"
     ]
    }
   ],
   "source": [
    "print(\"Descripción del dataset 'datos_creditos'\")\n",
    "reporte_descripcion_dataset(df_creditos)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Descripción del dataset 'datos_tarjetas'\n",
      "Columnas del dataset:\n",
      "\n",
      "id_cliente\n",
      "antiguedad_cliente\n",
      "estado_civil\n",
      "estado_cliente\n",
      "gastos_ult_12m\n",
      "genero\n",
      "limite_credito_tc\n",
      "nivel_educativo\n",
      "nivel_tarjeta\n",
      "operaciones_ult_12m\n",
      "personas_a_cargo\n",
      "\n",
      "Cantidad de filas: 10127\n"
     ]
    }
   ],
   "source": [
    "print(\"Descripción del dataset 'datos_tarjetas'\")\n",
    "reporte_descripcion_dataset(df_tarjetas)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "----\n",
    "\n",
    "##### Obtención de metadatos"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-12-05 21:46:57,052 - ERROR    - Exception occurred while processing request: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 186, in build\n",
      "    return_data, hist_labels = self.build_histogram_data(\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 162, in build_histogram_data\n",
      "    hist_data, hist_labels = np.histogram(series, **hist_kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 780, in histogram\n",
      "    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 426, in _get_bin_edges\n",
      "    first_edge, last_edge = _get_outer_edges(a, range)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 322, in _get_outer_edges\n",
      "    if not (np.isfinite(first_edge) and np.isfinite(last_edge)):\n",
      "TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "2023-12-05 21:47:24,056 - ERROR    - Exception occurred while processing request: Can only use .str accessor with string values!\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 458, in build\n",
      "    hist = self.build_hist(s, code)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 512, in build_hist\n",
      "    pd.value_counts(s.str.split(expand=True).stack())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/generic.py\", line 6204, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/accessor.py\", line 224, in __get__\n",
      "    accessor_obj = self._accessor(obj)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 190, in __init__\n",
      "    self._inferred_dtype = self._validate(data)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 244, in _validate\n",
      "    raise AttributeError(\"Can only use .str accessor with string values!\")\n",
      "AttributeError: Can only use .str accessor with string values!\n",
      "2023-12-05 21:47:59,374 - ERROR    - Exception occurred while processing request: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 186, in build\n",
      "    return_data, hist_labels = self.build_histogram_data(\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 162, in build_histogram_data\n",
      "    hist_data, hist_labels = np.histogram(series, **hist_kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 780, in histogram\n",
      "    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 426, in _get_bin_edges\n",
      "    first_edge, last_edge = _get_outer_edges(a, range)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 322, in _get_outer_edges\n",
      "    if not (np.isfinite(first_edge) and np.isfinite(last_edge)):\n",
      "TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "2023-12-05 21:50:31,028 - ERROR    - Exception occurred while processing request: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 186, in build\n",
      "    return_data, hist_labels = self.build_histogram_data(\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 162, in build_histogram_data\n",
      "    hist_data, hist_labels = np.histogram(series, **hist_kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 780, in histogram\n",
      "    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 426, in _get_bin_edges\n",
      "    first_edge, last_edge = _get_outer_edges(a, range)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 322, in _get_outer_edges\n",
      "    if not (np.isfinite(first_edge) and np.isfinite(last_edge)):\n",
      "TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "2023-12-05 21:51:08,668 - ERROR    - Exception occurred while processing request: Can only use .str accessor with string values!\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 458, in build\n",
      "    hist = self.build_hist(s, code)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 512, in build_hist\n",
      "    pd.value_counts(s.str.split(expand=True).stack())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/generic.py\", line 6204, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/accessor.py\", line 224, in __get__\n",
      "    accessor_obj = self._accessor(obj)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 190, in __init__\n",
      "    self._inferred_dtype = self._validate(data)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 244, in _validate\n",
      "    raise AttributeError(\"Can only use .str accessor with string values!\")\n",
      "AttributeError: Can only use .str accessor with string values!\n",
      "2023-12-05 21:51:23,007 - ERROR    - Exception occurred while processing request: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 186, in build\n",
      "    return_data, hist_labels = self.build_histogram_data(\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 162, in build_histogram_data\n",
      "    hist_data, hist_labels = np.histogram(series, **hist_kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 780, in histogram\n",
      "    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 426, in _get_bin_edges\n",
      "    first_edge, last_edge = _get_outer_edges(a, range)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 322, in _get_outer_edges\n",
      "    if not (np.isfinite(first_edge) and np.isfinite(last_edge)):\n",
      "TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "2023-12-05 21:51:27,350 - ERROR    - Exception occurred while processing request: Can only use .str accessor with string values!\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 458, in build\n",
      "    hist = self.build_hist(s, code)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 512, in build_hist\n",
      "    pd.value_counts(s.str.split(expand=True).stack())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/generic.py\", line 6204, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/accessor.py\", line 224, in __get__\n",
      "    accessor_obj = self._accessor(obj)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 190, in __init__\n",
      "    self._inferred_dtype = self._validate(data)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 244, in _validate\n",
      "    raise AttributeError(\"Can only use .str accessor with string values!\")\n",
      "AttributeError: Can only use .str accessor with string values!\n",
      "2023-12-05 21:51:43,235 - ERROR    - Exception occurred while processing request: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 186, in build\n",
      "    return_data, hist_labels = self.build_histogram_data(\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 162, in build_histogram_data\n",
      "    hist_data, hist_labels = np.histogram(series, **hist_kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 780, in histogram\n",
      "    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 426, in _get_bin_edges\n",
      "    first_edge, last_edge = _get_outer_edges(a, range)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/numpy/lib/histograms.py\", line 322, in _get_outer_edges\n",
      "    if not (np.isfinite(first_edge) and np.isfinite(last_edge)):\n",
      "TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''\n",
      "Exception ignored in: <function Image.__del__ at 0x7f266325ae60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 4056, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7f26633c36d0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 388, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7f26633c36d0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 388, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7f26633c36d0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 388, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "2023-12-05 21:52:18,865 - ERROR    - Exception occurred while processing request: Can only use .str accessor with string values!\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 119, in _handle_exceptions\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/views.py\", line 3110, in get_column_analysis\n",
      "    return jsonify(**analysis.build())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 142, in build\n",
      "    return_data, code = self.analysis.build(self)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 458, in build\n",
      "    hist = self.build_hist(s, code)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/dtale/column_analysis.py\", line 512, in build_hist\n",
      "    pd.value_counts(s.str.split(expand=True).stack())\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/generic.py\", line 6204, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/accessor.py\", line 224, in __get__\n",
      "    accessor_obj = self._accessor(obj)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 190, in __init__\n",
      "    self._inferred_dtype = self._validate(data)\n",
      "  File \"/home/sebastian/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py\", line 244, in _validate\n",
      "    raise AttributeError(\"Can only use .str accessor with string values!\")\n",
      "AttributeError: Can only use .str accessor with string values!\n"
     ]
    }
   ],
   "source": [
    "# Se usa la librería dtale para poder obtener una vista interactiva de los datos\n",
    "\n",
    "# Dataset: datos_creditos\n",
    "\n",
    "creditos = dt.show(df_creditos)\n",
    "creditos.open_browser()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dataset: datos_tarjetas\n",
    "\n",
    "tarjetas = dt.show(df_tarjetas)\n",
    "tarjetas.open_browser()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "----\n",
    "\n",
    "##### Gráficos de interés"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(7,5))\n",
    "sns.countplot(y=df_creditos['objetivo_credito'], order=df_creditos['objetivo_credito'].value_counts().index)\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10 (XPython Raw)",
   "language": "python",
   "name": "xpython-raw"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
